### ISSUE TITLE
제꺼두용 :)

### ISSUE THREAD

**Issue by jiminyun** [wphestiraid/nomadcoders-github-list#10]
**Slack Nickname:** _Your slack nickname here_

"JIMIN" 
https://github.com/jiminyun

**Comment by wphestiraid** [comment]
아니 지민님은 풀리퀘 날려주셔야죠!!!

**Comment by DalYoon** [comment]
Request has been completed

**Comment by mattdamon108** [comment]
언니 풀리퀘 할 줄 모르면 DM 줘요.

**Comment by jiminyun** [comment]
뭐냐 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 저요새 맥북을 안쓰고 있어가지고용. 윈도우 쓰니 타이핑도 힘듬 ㅠㅠ 근디 나
올라갔네??? 쌩유! 대디님~ 달윤님~ ㅋㅋㅋㅋㅋㅋㅋㅋ
