### ISSUE TITLE
저도 추가 부탁드려요.

### ISSUE THREAD

**Issue by Kioryu** [wphestiraid/nomadcoders-github-list#15]
**Slack Nickname:** _Your slack nickname here_

kioryu
https://github.com/kioryu

**Comment by wphestiraid** [comment]
안녕하세요. 혹시 슬랙 닉네임도 기재해주실 수 있으신가요?

**Comment by Kioryu** [comment]
kioryu입니다!

2019년 8월 10일 토요일, Flynn (Inho Park) <notifications@github.com>님이 작성:
