### ISSUE TITLE
추가 부탁드려요 ~ ^^ 싸랑해요 !!

### ISSUE THREAD

**Issue by Johnyworld** [wphestiraid/nomadcoders-github-list#17]
Slack Nickname: Johny Kim
Github : https://github.com/Johnyworld
Homepage : http://johnyworld.com
홈페이지는 그냥 적어봤습니다 :)

**Comment by DalYoon** [comment]
안녕하세요

**Comment by Johnyworld** [comment]
> 안녕하세요
> 슬랙에 해당 계정이 안보이는것 같은데 혹시 다른이름으로 등록되있으신가요

슬랙을 자주 안다뤄봐서 잘 몰랐는데, 이제 채널 가입했습니다! Johny Kim 으로 가입햇습니다!

**Comment by DalYoon** [comment]
넹 추가했습니다
