### ISSUE TITLE
Please add my github to the list. 추가 부탁드립니다

### ISSUE THREAD

**Issue by jenniexxi** [wphestiraid/nomadcoders-github-list#22]
**Slack Nickname:** _Your slack nickname here_

nickname :   Jiyeon Hong

**Comment by wphestiraid** [comment]
안녕하세요. 혹시 노마드코더 슬랙 닉네임도 기재해주실 수 있으신가요?

**Comment by jenniexxi** [comment]
슬랙 닉네임도 동일합니다. Jiyeon Hong  입니다.

**Comment by wphestiraid** [comment]
엇 죄송합니다 본문에 있었군요... ㅠ.ㅠ

**Comment by wphestiraid** [comment]
추가 완료했습니다~ 감사합니다
