### ISSUE TITLE
수정부탁드립니다..

### ISSUE THREAD

**Issue by sikim0726** [wphestiraid/nomadcoders-github-list#33]
**Slack Nickname:** _sihyun_

슬랙 닉네임 sihyun이고..
아이디를 변경해서 github주소가 https://github.com/skim0726이 아닌, github.com/sikim0726으로 바뀌었습니다.

풀리퀘 하는방법을 몰라서리..ㅠㅠ

**Comment by wphestiraid** [comment]
완료처리 됐습니다~
